### ISSUE TITLE
Inaccurate libnv bindings

### ISSUE THREAD

**Issue by asomers** [Inner-Heaven/libnv-rs#13]
I noticed several type errors in the FFI bindings in libnv-sys/src/lib.rs.  For example
```rust
    pub fn nvlist_add_binary(list: *mut nvlist, name: *const i8, value: *mut i8, size: u32) -> ();
```
should be
```rust
    pub fn nvlist_add_binary(nvl: *mut nvlist, name: *const c_char, value: *const c_void, size: usize) -> ();
```
I suggest automatically generating the bindings.

**Comment by andoriyu** [comment]
This is closed in #14, right?

**Comment by andoriyu** [comment]
i'm pretty sure i've generated bindings using bindgen, but it was so long ago that travis was still a popular CI.

**Comment by asomers** [comment]
Yeah, that PR fixed it.
