### ISSUE TITLE
Linkage conflict with libcasper on FreeBSD 14

### ISSUE THREAD

**Issue by asomers** [Inner-Heaven/libnv-rs#16]
In #12 I forced libnv-sys to always link to libnv.so.0, even if a newer one were present.  I thought that would provide good backwards-compatibility and also cross-compilability.  However, I failed to consider interactions with other native libraries.  For example, on FreeBSD 14 libcasper.so.1 is already linked to libnv.so.1.  Trying to build a Rust program that uses both libcasper-sys (not yet published) and libnv-sys will result in linking to both libnv.so.1 and libnv.so.0.  That's obviously not good.  We don't want to for example allocate an NVList using one library and destroy it using the other.
I'll need to rethink this.  Right now I can only think of two solutions:
* Run bindgen at build time, which breaks cross-compiling and pulls in extra dependencies, or
* Drop support for libnv.so.0, which means all stable releases of FreeBSD.

**Comment by andoriyu** [comment]
I'm fine with dropping support for `libnv.so.0`. When I started on this, I always planned only to support latest releases. If someone need older version - they can grab older `libnv`.

@asomers you've already started on the solution? We can also use features to choose library, it's error-prone, but backwards-compatible solution.

**Comment by andoriyu** [comment]
Once the solution is implemented, I will cut a new release for all crates related.

**Comment by asomers** [comment]
Do you realize that FreeBSD 14 hasn't been released yet?  13.1 is the latest stable release, and it has libnv.so.0.  I think the best solution is to generate bindings at build-time.  I'm already working on it.

**Comment by andoriyu** [comment]
My bad, I've confused it with Ruby that had release every xmas.

I prefer to keep cross-compiling possible and easy, but since you're have
already started, I guess it fine to do build time bindings.
