### ISSUE TITLE
CStr in public APIs

### ISSUE THREAD

**Issue by asomers** [Inner-Heaven/libnv-rs#18]
libnv's current API expects `&str` for all names and string-like values.  It then internally converts them to `CString`.  But sometimes it's necessary to insert a name or value that's already a `&CStr`, for example when a C function calls into Rust.  It would be more efficient and ergonomic if libnv could accept those, too.  Something like this:
```rust
pub trait IntoCStr {
    fn into_cstr(self) -> NvResult<Cow<CStr>> {
        ...
    }
}
impl IntoCStr for &str {...}
impl IntoCStr for &CStr {...}
impl NvList {
    fn insert_string<N: IntoCStr, V: IntoCStr>(&mut self, name: N, value: V) -> NvResult<()> {
        ...
    }
}
```

**Comment by andoriyu** [comment]
Makes sense. If you haven't already started on this, i would like to work on this.

**Comment by asomers** [comment]
No, I haven't started on it yet.  But BTW I'm close to having the bindgen stuff working on both 13 and 14.

**Comment by andoriyu** [comment]
Going to work on this later this week.
