### ISSUE TITLE
Release libnv-sys, please

### ISSUE THREAD

**Issue by asomers** [Inner-Heaven/libnv-rs#26]
I see that you recently released libnv-0.4.0.  Would you please publish a new release of libnv-sys, too?

**Comment by andoriyu** [comment]
Oh, totally forgot about it. Need to yank 0.4.0 and re-release it. My bad.

**Comment by andoriyu** [comment]
Done. Released it as 0.2.0, yanked libnv 0.4.0 and published 0.4.1 with updated dependency.

**Comment by asomers** [comment]
Thanks!
